scienceAndEngineeringSubCategoriesKitapyurdu = [
  'Bilim Tarihi',
  'Astronomi',
  'Bilim İnsanları',
  'Coğrafya',
  'Kuramsal Kitaplar & Matematik',
  'Metodoloji',
  'Popüler Bilim',
  'Sosyal Bilimler',
  'Teknoloji & Teknik Kitaplar',
  'Uygulamalı Bilimler & Mühendislik',
  'Diğer',
]

scienceAndEngineeringLinksKitapyurdu = [
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_238',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_247',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_239',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_243',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_237',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_242',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_240',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_246',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_245',
  'https://www.kitapyurdu.com/index.php?route=product/category&path=236_241',
  'https://www.kitapyurdu.com/kategori/kitap-bilim-amp-muhendislik/236.html',
]

examsSubCategoriesKitapyurdu = [
  'Adalet Bakanlığı Sınavları',
  'ALES',
  'Askeri Okullar Sınavları',
  'DGS',
  'GYS - Görevde Yükselme Sınavları',
  'KPSS - Alan Bilgisi',
  'KPSS - DHBT',
  'KPSS - Eğitim Bilimleri',
  'KPSS - EKPSS',
  'KPSS - Genel Yetenek & Genel Kültür',
  'KPSS A',
  'KPSS B',
  'ÖABT',
  'LGS - Liselere Geçiş Sınavı',
  'MEB - Açık Öğretim',
  'MEB - BİLSEM',
  'MEB - İOKBS Bursluluk',
  'MEB - Öğretmen Sınavları',
  'Polis Okulları Sınavları',
  'SMMM - YMM',
  'SPK - SPF',
  'Uzmanlık Sınavları (TUS & DUS & EUS)',
  'Yabancı Dil Sınavları - TOEFL',
  'Yabancı Dil Sınavları - YDS',
  'Yabancı Dil Sınavları - YÖKDİL',
  'Yabancı Dil Sınavları - Diğer',
  'YKS AYT - Alan Yeterlilik Testleri',
  'YKS TYT - Temel Yeterlilik Testi',
  'YKS YDT - Yabancı Dil Testi',
  'Banka Sınavları',
  'İSG - İş Güvenliği',
  'Kaymakamlık',
  'LYS',
  'Milli İzleme Sınavı',
  'OKS - SBS',
  'ÖSS',
  'TEOG',
  'Üniversite Giriş Sınavı',
  'YGS',
]

examsLinksKitapyurdu = [
  'https://www.kitapyurdu.com/kategori/sinavlar-adalet-bakanligi-sinavlari/737_959.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-ales/737_740.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-askeri-okullar-sinavlari/737_746.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-dgs/737_743.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-gys--gorevde-yukselme-sinavlari/737_949.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-alan-bilgisi/737_739_1122.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-dhbt/737_739_948.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-egitim-bilimleri/737_739_951.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-ekpss/737_739_1120.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-genel-yetenek--genel-kultur/737_739_952.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-kpss-a/737_739_953.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-kpss-b/737_739_1055.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-kpss-oabt/737_739_950.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-lgs---liselere-gecis-sinavi/737_1073.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-meb-sinavlari-acik-ogretim/737_1130_1133.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-meb-sinavlari-bilsem/737_1130_1132.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-meb-sinavlari-iokbs-bursluluk/737_1130_1131.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-meb-sinavlari-ogretmen-sinavlari/737_1130_748.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-polis-okullari-sinavlari/737_747.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-smmm--ymm/737_958.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-spk--spf/737_741.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-uzmanlik-sinavlari/737_744.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yabanci-dil-sinavlari-toefl/737_742_1124.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yabanci-dil-sinavlari-yds/737_742_1123.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yabanci-dil-sinavlari-yokdil/737_742_1125.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yabanci-dil-sinavlari-diger-sinavlar/737_742_1126.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yks--yuksekogretim-kurumlari-sinavi-yks-ayt--alan-yeterlilik-testleri/737_1067_1082.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yks--yuksekogretim-kurumlari-sinavi-yks-tyt--temel-yeterlilik-testi/737_1067_1068.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-yks--yuksekogretim-kurumlari-sinavi-yks-ydt--yabanci-dil-testi/737_1067_1104.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-banka-sinavlari/737_750_947.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-isg--is-guvenligi/737_750_1127.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-kaymakamlik/737_750_1128.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-lys/737_750_752.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-milli-izleme-sinavi/737_750_1066.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-oks--sbs/737_750_749.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-oss/737_750_738.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-teog/737_750_957.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-universite-giris-sinavi/737_750_1071.html',
  'https://www.kitapyurdu.com/kategori/sinavlar-diger-sinavlar-ygs/737_750_751.html',
]

literatureSubCategoriesKitapyurdu = [
  '100 Temel Eser',
  'Anı (hatırat)',
  'Anlatı',
  'Antoloji-Derleme',
  'Armağan',
  'Belgesel Roman',
  'Bilimkurgu-Fantazya',
  'Biyografi-Otobiyografi',
  'Çizgi Roman',
  'Deneme (çeviri)',
  'Deneme (yerli)',
  'Destan',
  'Divan Edebiyatı',
  'Doğu Klasikleri',
  'Edebiyat Tarihi',
  'Edebiyat Yazıları',
  'Eleştiri',
  'Günlük',
  'Halk Edebiyatı',
  'Hiciv-Mizah',
  'Hikaye (çeviri)',
  'Hikaye (yerli)',
  'Hitabet-Söyleşi',
  'İnceleme',
  'Korku Gerilim',
  'Mektup',
  'Polemik',
  'Polisiye',
  'Roman (çeviri)',
  'Roman (yerli)',
  'Şiir (çeviri)',
  'Şiir (yerli)',
  'Tarihi Roman',
  'Diğer',
]

literatureLinksKitapyurdu = [
  'https://www.kitapyurdu.com/kategori/edebiyat-100-temel-eser-/128_1233.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-ani-hatirat/128_140.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-anlati/128_158.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-antolojiderleme/128_139.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-armagan/128_155.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-belgesel-roman/128_150.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-bilimkurgufantazya/128_145.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-biyografiotobiyografi/128_141.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-cizgi-roman/128_159.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-deneme-ceviri/128_136.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-deneme-yerli/128_135.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-destan/128_160.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-divan-edebiyati/128_148.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-dogu-klasikleri/128_146.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-edebiyat-tarihi/128_149.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-edebiyat-yazilari/128_157.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-elestiri/128_137.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-gunluk/128_142.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-halk-edebiyati/128_147.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-hicivmizah/128_156.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-hikaye-ceviri/128_132.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-hikaye-yerli/128_131.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-hitabetsoylesi/128_153.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-inceleme/128_138.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-korku-gerilim/128_1430.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-mektup/128_143.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-polemik/128_152.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-polisiye/128_144.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-roman-ceviri/128_130.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-roman-yerli/128_129.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-siir-ceviri/128_134.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-siir-yerli/128_133.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-tarihi-roman/128_151.html',
  'https://www.kitapyurdu.com/kategori/edebiyat-diger/128_154.html',
]

lawSubCategoriesKitapyurdu = [
  'Temel Kitaplar',
  'Anayasalar',
  'Haklar ve Özgürlükler',
  'İnsan Hakları',
  'Kanun Kitapları',
  'Mevzuat Kitapları',
  'Ders Kitapları',
  'Önemli Olaylar/Davalar',
  'Diğer',
]

lawLinksKitapyurdu = [
  'https://www.kitapyurdu.com/kategori/hukuk-temel-kitaplar/248_249.html',
  'https://www.kitapyurdu.com/kategori/hukuk-anayasalar/248_250.html',
  'https://www.kitapyurdu.com/kategori/hukuk-haklar-ve-ozgurlukler/248_257.html',
  'https://www.kitapyurdu.com/kategori/hukuk-insan-haklari/248_254.html',
  'https://www.kitapyurdu.com/kategori/hukuk-kanun-kitaplari/248_251.html',
  'https://www.kitapyurdu.com/kategori/hukuk-mevzuat-kitaplari/248_252.html',
  'https://www.kitapyurdu.com/kategori/hukuk-ders-kitaplari/248_253.html',
  'https://www.kitapyurdu.com/kategori/hukuk-onemli-olaylardavalar/248_255.html',
  'https://www.kitapyurdu.com/kategori/hukuk-diger/248_256.html',
]

philosophySubCategoriesKitapyurdu = [
  'Felsefe Bilimi',
  'Felsefe Tarihi',
  'Felsefe Metinleri',
  'Filozoflar-Düşünürler',
  'Akımlar',
  'Doğu Felsefesi',
  'Mantık',
  'Siyaset Felsefesi',
  'Etik-Ahlak',
  'Estetik',
  'Genel',
  'Diğer',
]

philosophyLinksKitapyurdu = [
  'https://www.kitapyurdu.com/kategori/felsefedusunce-felsefe-bilimi/424_431.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-felsefe-tarihi/424_426.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-felsefe-metinleri/424_433.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-filozoflardusunurler/424_427.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-akimlar/424_425.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-dogu-felsefesi/424_434.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-mantik/424_430.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-siyaset-felsefesi/424_435.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-etikahlak/424_428.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-estetik/424_429.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-genel/424_432.html',
  'https://www.kitapyurdu.com/kategori/felsefedusunce-diger/424_1032.html',
]

economySubCategoriesKitapyurdu = [
  'Doktrinler',
  'Tarih',
  'Sistemler',
  'Bilim',
  'Pazarlama-Satış',
  'Örgütler',
  'Biyografi',
  'Muhasebe-Maliye',
  'Küreselleşme',
  'Ticaret',
  'Borsa',
  'Kurumlar',
  'Kuram',
  'Türkiye Ekonomisi',
  'Terimler-Kavramlar',
  'İş Dünyası',
  'İnceleme-Araştırma',
  'Finans',
  'Dünya Ekonomisi',
  'Vergi',
  'İşletme',
  'Çalışma Hayatı',
  'Diğer',
]

economyLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/ekonomi-doktrinler/380_385.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-tarih/380_383.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-sistemler/380_386.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-bilim/380_382.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-pazarlamasatis/380_391.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-orgutler/380_388.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-biyografi/380_984.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-muhasebemaliye/380_392.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-kuresellesme/380_398.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-ticaret/380_402.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-borsa/380_395.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-kurumlar/380_387.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-kuram/380_381.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-turkiye-ekonomisi/380_396.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-terimlerkavramlar/380_384.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-is-dunyasi/380_389.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-incelemearastirma/380_401.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-finans/380_394.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-dunya-ekonomisi/380_397.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-vergi/380_400.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-isletme/380_393.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-calisma-hayati/380_390.html",
  "https://www.kitapyurdu.com/kategori/ekonomi-diger/380_399.html",
]

artSubCategoriesKitapyurdu = [
  "Mimari",
  "Sanat Tarihi",
  "Resim - Akımlar",
  "Resim Teknikleri",
  "Resim - Genel",
  "Ressamlar",
  "Kuram",
  "Heykel",
  "Grafik",
  "Geleneksel Sanat",
  "Fotoğraf",
  "Genel",
  "Diğer",
]

artLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/sanat-mimari/172_181.html",
  "https://www.kitapyurdu.com/kategori/sanat-sanat-tarihi/172_184.html",
  "https://www.kitapyurdu.com/kategori/sanat-resim-akimlar/172_174_175.html",
  "https://www.kitapyurdu.com/kategori/sanat-resim-resim-teknikleri/172_174_177.html",
  "https://www.kitapyurdu.com/kategori/sanat-resim-genel/172_174_176.html",
  "https://www.kitapyurdu.com/kategori/sanat-resim-ressamlar/172_174_178.html",
  "https://www.kitapyurdu.com/kategori/sanat-kuram/172_1060.html",
  "https://www.kitapyurdu.com/kategori/sanat-heykel/172_179.html",
  "https://www.kitapyurdu.com/kategori/sanat-grafik/172_182.html",
  "https://www.kitapyurdu.com/kategori/sanat-geleneksel-sanatlar/172_185.html",
  "https://www.kitapyurdu.com/kategori/sanat-fotograf/172_183.html",
  "https://www.kitapyurdu.com/kategori/sanat-genel/172_173.html",
  "https://www.kitapyurdu.com/kategori/sanat-diger/172_180.html",
]

sociologySubCategoriesKitapyurdu = [
  "İnceleme-Araştırma",
  "Sosyoloji Yazıları",
  "Bilim",
  "Sosyologlar",
  "Kavramlar",
  "Din Sosyolojisi",
  "Kentleşme",
  "Diğer",
]

sociologyLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/sosyoloji-incelemearastirma/415_417.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-sosyoloji-yazilari/415_422.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-bilim/415_416.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-sosyologlar/415_420.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-kavramlar/415_421.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-din-sosyolojisi/415_419.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-kentlesme/415_418.html",
  "https://www.kitapyurdu.com/kategori/sosyoloji-diger/415_423.html",
]

politicsSubCategoriesKitapyurdu = [
  "Etnik Sorunlar",
  "Kıbrıs",
  "Güncel Sorunlar",
  "Uluslararası Siyaset",
  "Terör-Mafya",
  "Araştırma-İnceleme",
  "Siyasi Kurgu",
  "Kurumlar-Örgütler",
  "Siyaset Bilimi",
  "Biyografi-Otobiyografi",
  "Siyasal Yazılar - Tezler",
  "Siyasal Tarih",
  "Siyasal Partiler",
  "Anı",
  "Siyasal Hayat (Türkiye)",
  "Siyasal Hayat (Dünya)",
  "Atatürk",
  "Siyasal Akımlar",
  "Savaşlar",
  "Kuram",
  "İdare",
  "Hatıralar",
  "Siyasal Hareketler-Eylemler-Topluluklar",
  "Siyasal Sistemler",
  "Bölgeler-Ülkeler",
  "Anlaşmalar-Kongreler",
  "Devlet",
  "Siyasal Düşünce",
  "Aktüel Siyaset",
  "Diğer",
]

politicsLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/siyaset-etnik-sorunlar/98_118.html",
  "https://www.kitapyurdu.com/kategori/siyaset-kibris/98_127.html",
  "https://www.kitapyurdu.com/kategori/siyaset-guncel-sorunlar/98_123.html",
  "https://www.kitapyurdu.com/kategori/siyaset-uluslararasi-siyaset/98_113.html",
  "https://www.kitapyurdu.com/kategori/siyaset-terormafya/98_122.html",
  "https://www.kitapyurdu.com/kategori/siyaset-arastirmainceleme/98_125.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasi-kurgu/98_126.html",
  "https://www.kitapyurdu.com/kategori/siyaset-kurumlarorgutler/98_104.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyaset-bilimi/98_100.html",
  "https://www.kitapyurdu.com/kategori/siyaset-biyografiotobiyografi/98_117.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-yazilar--tezler/98_110.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-tarih/98_111.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-partiler/98_105.html",
  "https://www.kitapyurdu.com/kategori/siyaset-ani/98_1242.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-hayat-turkiye/98_114.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-hayat-dunya/98_115.html",
  "https://www.kitapyurdu.com/kategori/siyaset-mustafa-kemal-ataturk/98_124.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-akimlar/98_107.html",
  "https://www.kitapyurdu.com/kategori/siyaset-savaslar/98_120.html",
  "https://www.kitapyurdu.com/kategori/siyaset-kuram/98_99.html",
  "https://www.kitapyurdu.com/kategori/siyaset-idare/98_102.html",
  "https://www.kitapyurdu.com/kategori/siyaset-hatiralar/98_116.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-hareketlereylemlertopluluklar/98_108.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-sistemler/98_106.html",
  "https://www.kitapyurdu.com/kategori/siyaset-bolgelerulkeler/98_119.html",
  "https://www.kitapyurdu.com/kategori/siyaset-anlasmalarkongreler/98_103.html",
  "https://www.kitapyurdu.com/kategori/siyaset-devlet/98_101.html",
  "https://www.kitapyurdu.com/kategori/siyaset-siyasal-dusunce/98_112.html",
  "https://www.kitapyurdu.com/kategori/siyaset-aktuel-siyaset/98_109.html",
  "https://www.kitapyurdu.com/kategori/siyaset-diger/98_121.html",
]

historySubCategoriesKitapyurdu = [
  "Çağlar-Dönemler",
  "Önemli Olaylar",
  "Medeniyetler",
  "Kuram",
  "Kronolojiler",
  "İnceleme-Araştırma",
  "Kişiler",
  "Keşifler Tarihi",
  "Yerel Tarih",
  "Hatıralar",
  "Dünya",
  "Türkiye",
  "Türk-Osmanlı",
  "Bilim Tarihi",
  "Bölgeler-Ülkeler",
  "Yöntem",
  "Bilim",
  "Seyahatname",
  "Siyasal Tarih",
  "Belgeler",
  "Diğer",
]

historyLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/tarih-caglardonemler/41_48.html",
  "https://www.kitapyurdu.com/kategori/tarih-onemli-olaylar/41_61.html",
  "https://www.kitapyurdu.com/kategori/tarih-medeniyetler/41_60.html",
  "https://www.kitapyurdu.com/kategori/tarih-kuram/41_42.html",
  "https://www.kitapyurdu.com/kategori/tarih-kronolojiler/41_58.html",
  "https://www.kitapyurdu.com/kategori/tarih-incelemearastirma/41_63.html",
  "https://www.kitapyurdu.com/kategori/tarih-kisiler/41_56.html",
  "https://www.kitapyurdu.com/kategori/tarih-kesifler-tarihi/41_54.html",
  "https://www.kitapyurdu.com/kategori/tarih-yerel-tarih/41_52.html",
  "https://www.kitapyurdu.com/kategori/tarih-hatiralar/41_55.html",
  "https://www.kitapyurdu.com/kategori/tarih-dunya/41_47.html",
  "https://www.kitapyurdu.com/kategori/tarih-turkiye/41_46.html",
  "https://www.kitapyurdu.com/kategori/tarih-turkosmanli/41_45.html",
  "https://www.kitapyurdu.com/kategori/tarih-bilim-tarihi/41_53.html",
  "https://www.kitapyurdu.com/kategori/tarih-bolgelerulkeler/41_59.html",
  "https://www.kitapyurdu.com/kategori/tarih-yontem/41_44.html",
  "https://www.kitapyurdu.com/kategori/tarih-bilim/41_43.html",
  "https://www.kitapyurdu.com/kategori/tarih-seyahatname/41_57.html",
  "https://www.kitapyurdu.com/kategori/tarih-siyasal-tarih/41_50.html",
  "https://www.kitapyurdu.com/kategori/tarih-belgeler/41_49.html",
  "https://www.kitapyurdu.com/kategori/tarih-diger/41_62.html",
]

computerSubCategoriesKitapyurdu = [
  "Kavramlar",
  "Network",
  "İnternet",
  "Donanım",
  "Program Eğitimi",
  "Genel",
  "Diğer",
]

computerLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/bilgisayar-kavramlar/31_32.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-network/31_34.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-internet/31_35.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-donanim/31_38.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-program-egitimi/31_33.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-genel/31_40.html",
  "https://www.kitapyurdu.com/kategori/bilgisayar-diger/31_37.html",
]

childrenSubCategoriesKitapyurdu = [
  "Hikaye",
  "Çizgi Roman",
  "Şiir",
  "Roman",
  "Piyes",
  "Okul Öncesi",
  "Kaynak Kitaplar",
  "Fıkra, Eğlence & Oyun",
  "12 + Yaş",
  "6-12 Yaş",
  "100 Temel Eser",
]

childrenLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-hikaye/2_3.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-cizgi-roman/2_28.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-siir/2_18.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-roman/2_4.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-piyes/2_26.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-okul-oncesi/2_5.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-kaynak-kitaplar/2_13.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-fikra-eglence-amp-oyun/2_11.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-12--yas/2_22.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-612-yas/2_19.html",
  "https://www.kitapyurdu.com/kategori/cocuk-kitaplari-100-temel-eser/2_27.html",
]

healthSubCategoriesKitapyurdu = [
  "Eğitim",
  "Toplum Sağlığı",
  "Sağlıklı Yaşam",
  "Sağlıklı beslenme-Diyet",
  "Meditasyon-Yoga",
  "Cinsellik",
  "İlk Yardım",
  "El Kitapları",
  "Şifalı Bitkiler",
  "Biyografi",
  "Hatıralar",
  "Alternatif Tıp",
  "Genel",
  "Diğer",
]

healthLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/sagliktip-egitim/344_358.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-toplum-sagligi/344_357.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-saglikli-yasam/344_346.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-saglikli-beslenmediyet/344_349.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-meditasyonyoga/344_348.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-cinsellik/344_347.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-ilk-yardim/344_352.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-el-kitaplari/344_351.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-sifali-bitkiler/344_350.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-biyografi/344_354.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-hatiralar/344_353.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-alternatif-tip/344_355.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-genel/344_345.html",
  "https://www.kitapyurdu.com/kategori/sagliktip-diger/344_356.html",
]

hobbySubCategoriesKitapyurdu = [
  "Bahçe",
  "Bitkiler",
  "Spor",
  "El İşleri",
  "Boyama",
  "Yeme-İçme",
  "Oyunlar",
  "Denizcilik",
  "El Sanatları",
  "Diğer",
]

hobbyLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/hobi-bahce/212_215.html",
  "https://www.kitapyurdu.com/kategori/hobi-bitkiler/212_216.html",
  "https://www.kitapyurdu.com/kategori/hobi-spor/212_1036.html",
  "https://www.kitapyurdu.com/kategori/hobi-el-isleri/212_219.html",
  "https://www.kitapyurdu.com/kategori/hobi-boyama/212_963.html",
  "https://www.kitapyurdu.com/kategori/hobi-yemeicme/212_217.html",
  "https://www.kitapyurdu.com/kategori/hobi-oyunlar/212_220.html",
  "https://www.kitapyurdu.com/kategori/hobi-denizcilik/212_223.html",
  "https://www.kitapyurdu.com/kategori/hobi-el-sanatlari/212_218.html",
  "https://www.kitapyurdu.com/kategori/hobi-diger/212_221.html",
]

communicationSubCategoriesKitapyurdu = [
  "İletişim-Medya",
  "Reklamcılık-Halkla İlişkiler",
  "Enformasyon",
]

communicationLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/diger-iletisimmedya/319_329.html",
  "https://www.kitapyurdu.com/kategori/diger-reklamcilikhalkla-iliskiler/319_332.html",
  "https://www.kitapyurdu.com/kategori/diger-enformasyon/319_328.html",
]

sportsSubCategoriesKitapyurdu = [
  "Basketbol",
  "Tarih",
  "Futbol",
  "Spor Dalları",
  "Biyografi",
  "Beyin Sporları",
  "Genel",
]

sportsLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/spor-basketbol/196.html",
  "https://www.kitapyurdu.com/kategori/spor-tarih/197.html",
  "https://www.kitapyurdu.com/kategori/spor-futbol/195.html",
  "https://www.kitapyurdu.com/kategori/spor-dallari/198.html",
  "https://www.kitapyurdu.com/kategori/spor-biyografi/189.html",
  "https://www.kitapyurdu.com/kategori/spor-beyin-sporlari/194.html",
  "https://www.kitapyurdu.com/kategori/spor-genel/191.html",
]

tourismSubCategoriesKitapyurdu = [
  "Rehber",
  "Gezi Kitapları",
  "Gezginler",
  "Şehirler-Bölgeler",
  "Ülkeler",
  "Turistik Bölgeler-Bilgiler (Türkiye)",
  "Tarihi Mekanlar (Türkiye)",
  "Tarihi Mekanlar (Dünya)",
  "Harita",
  "Diğer",
]

tourismLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/turizmgezi-rehber/403_404.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-gezi-kitaplari/403_407.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-gezginler/403_414.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-sehirlerbolgeler/403_412.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-ulkeler/403_411.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-turistik-bolgelerbilgiler-turkiye/403_410.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-tarihi-mekanlar-turkiye/403_408.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-tarihi-mekanlar-dunya/403_409.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-harita/403_405.html",
  "https://www.kitapyurdu.com/kategori/turizmgezi-diger/403_413.html",
]

musicSubCategoriesKitapyurdu = [
  "Kavram-Kuram",
  "Eğitim-Öğretim",
  "Nota Kitapları",
  "Dans",
  "Enstrümanlar",
  "Müzisyenler",
  "Şarkılar-Türküler",
  "Tarih",
  "Genel",
]

musicLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/muzik-kavramkuram/161_165.html",
  "https://www.kitapyurdu.com/kategori/muzik-egitimogretim/161_164.html",
  "https://www.kitapyurdu.com/kategori/muzik-nota-kitaplari/161_169.html",
  "https://www.kitapyurdu.com/kategori/muzik-dans/161_171.html",
  "https://www.kitapyurdu.com/kategori/muzik-enstrumanlar/161_166.html",
  "https://www.kitapyurdu.com/kategori/muzik-muzisyenler/161_168.html",
  "https://www.kitapyurdu.com/kategori/muzik-sarkilarturkuler/161_170.html",
  "https://www.kitapyurdu.com/kategori/muzik-tarih/161_163.html",
  "https://www.kitapyurdu.com/kategori/muzik-genel/161_162.html",
]

entertainmentSubCategoriesKitapyurdu = [
  "Karikatür",
  "Oyun",
  "Fıkra",
  "Çizgi Roman",
  "Antoloji",
  "Bilmece-Bulmaca",
  "Genel",
  "Diğer",
]

entertainmentLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/eglencemizah-karikatur/371_374.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-oyun/371_375.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-fikra/371_377.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-cizgi-roman/371_373.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-antoloji/371_378.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-bilmecebulmaca/371_376.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-genel/371_372.html",
  "https://www.kitapyurdu.com/kategori/eglencemizah-diger/371_379.html",
]

cinemaSubCategoriesKitapyurdu = [
  "Sinema - Genel",
  "Tiyatro - Genel",
  "Senaryo - Yerli",
  "Senaryo - Çeviri",
  "Oyun - Yerli",
  "Oyun - Çeviri",
]

cinemaLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/sinematiyatro-sinemagenel/724_729.html",
  "https://www.kitapyurdu.com/kategori/sinematiyatro-tiyatrogenel/724_730.html",
  "https://www.kitapyurdu.com/kategori/sinematiyatro-senaryo-yerli/724_728.html",
  "https://www.kitapyurdu.com/kategori/sinematiyatro-senaryo-ceviri/724_727.html",
  "https://www.kitapyurdu.com/kategori/sinematiyatro-oyun-yerli/724_726.html",
  "https://www.kitapyurdu.com/kategori/sinematiyatro-oyun-ceviri/724_725.html",
]

psychologySubCategoriesKitapyurdu = [
  "Toplum Psikolojisi",
  "Psikolojik Danışma",
  "Çocuk Psikolojisi",
  "Yöntem",
  "Bilim",
  "Yaklaşımlar",
  "Biyografi",
  "Psikoloji Tarihi",
  "İnceleme",
  "Genel",
]

psychologyLinksKitapyurdu = [
  "https://www.kitapyurdu.com/kategori/psikoloji-toplum-psikolojisi/87_95.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-psikolojik-danisma/87_93.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-cocuk-psikolojisi/87_97.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-yontem/87_89.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-bilim/87_88.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-yaklasimlar/87_90.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-biyografi/87_94.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-psikoloji-tarihi/87_92.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-inceleme/87_91.html",
  "https://www.kitapyurdu.com/kategori/psikoloji-genel/87_96.html",
]

allSubCategoriesKitapyurdu = [
  scienceAndEngineeringSubCategoriesKitapyurdu,
  examsSubCategoriesKitapyurdu,
  literatureSubCategoriesKitapyurdu,
  lawSubCategoriesKitapyurdu,
  philosophySubCategoriesKitapyurdu,
  economySubCategoriesKitapyurdu,
  artSubCategoriesKitapyurdu,
  sociologySubCategoriesKitapyurdu,
  politicsSubCategoriesKitapyurdu,
  historySubCategoriesKitapyurdu,
  computerSubCategoriesKitapyurdu,
  childrenSubCategoriesKitapyurdu,
  healthSubCategoriesKitapyurdu,
  hobbySubCategoriesKitapyurdu,
  communicationSubCategoriesKitapyurdu,
  sportsSubCategoriesKitapyurdu,
  tourismSubCategoriesKitapyurdu,
  musicSubCategoriesKitapyurdu,
  entertainmentSubCategoriesKitapyurdu,
  cinemaSubCategoriesKitapyurdu,
  psychologySubCategoriesKitapyurdu
]

allLinksKitapyurdu = [
  scienceAndEngineeringLinksKitapyurdu,
  examsLinksKitapyurdu,
  literatureLinksKitapyurdu,
  lawLinksKitapyurdu,
  philosophyLinksKitapyurdu,
  economyLinksKitapyurdu,
  artLinksKitapyurdu,
  sociologyLinksKitapyurdu,
  politicsLinksKitapyurdu,
  historyLinksKitapyurdu,
  computerLinksKitapyurdu,
  childrenLinksKitapyurdu,
  healthLinksKitapyurdu,
  hobbyLinksKitapyurdu,
  communicationLinksKitapyurdu,
  sportsLinksKitapyurdu,
  tourismLinksKitapyurdu,
  musicLinksKitapyurdu,
  entertainmentLinksKitapyurdu,
  cinemaLinksKitapyurdu,
  psychologyLinksKitapyurdu
]